name: 'AKeyless Integrations'
description: 'Login and fetch secrets from AKeyless'
author: "Lance McCarthy, Connor Mancone"
branding:
  icon: 'unlock'
  color: 'green'
inputs:
  access-id:
    description: 'The access id of your auth method.'
    required: true
  access-type:
    description: 'Access type for login (JWT|AWS_IAM|GCP).'
    default: 'JWT'
    required: false
  api-url:
    description: 'API endpoint to login/fetch secrets from.'
    default: 'https://api.akeyless.io'
    required: false
  producer-for-aws-access:
    description: 'Path to an AWS dynamic producer in AKeyless (AWS access will be configured with it).'
    default: ''
    required: false
  static-secrets:
    description: 'Static secrets to fetch from AKeyless (should be a dictionary with the secret path as the key and the destination output/ENV as the value).'
    required: false
  dynamic-secrets:
    description: 'Dynamic secrets to fetch from AKeyless (should be a dictionary with the secret path as the key and the destination output/ENV as the value).'
    required: false
  export-secrets-to-outputs:
    description: 'Whether or not to export the extracted secrets to job outputs.'
    required: false
    default: true
  export-secrets-to-environment:
    description: 'Whether or not to export the extracted secrets to the environment.'
    required: false
    default: true
  separate-dynamic-secrets:
    description: 'Dynamic secrets get exported as a single JSON object. This switch will let you get separate output/env variables for each key.'
    required: false
    default: false
runs:
  using: 'node16'
  main: 'src/index.js'
